// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: barbershop_chains.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBarberShopChains = `-- name: CreateBarberShopChains :one
INSERT INTO "BarberShopChains" ("name", "founder", "founding_date", website)
VALUES ($1, $2, $3, $4)
RETURNING id, name, chain_identifier, founder, founding_date, website
`

type CreateBarberShopChainsParams struct {
	Name         string         `json:"name"`
	Founder      string         `json:"founder"`
	FoundingDate time.Time      `json:"founding_date"`
	Website      sql.NullString `json:"website"`
}

func (q *Queries) CreateBarberShopChains(ctx context.Context, arg CreateBarberShopChainsParams) (BarberShopChain, error) {
	row := q.db.QueryRowContext(ctx, createBarberShopChains,
		arg.Name,
		arg.Founder,
		arg.FoundingDate,
		arg.Website,
	)
	var i BarberShopChain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChainIdentifier,
		&i.Founder,
		&i.FoundingDate,
		&i.Website,
	)
	return i, err
}

const deleteBarberShopChains = `-- name: DeleteBarberShopChains :exec
DELETE FROM "BarberShopChains"
WHERE "id" = $1
`

func (q *Queries) DeleteBarberShopChains(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBarberShopChains, id)
	return err
}

const getBarberShopChains = `-- name: GetBarberShopChains :one
SELECT id, name, chain_identifier, founder, founding_date, website
FROM "BarberShopChains"
WHERE "id" = $1
`

func (q *Queries) GetBarberShopChains(ctx context.Context, id uuid.UUID) (BarberShopChain, error) {
	row := q.db.QueryRowContext(ctx, getBarberShopChains, id)
	var i BarberShopChain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChainIdentifier,
		&i.Founder,
		&i.FoundingDate,
		&i.Website,
	)
	return i, err
}

const updateBarberShopChains = `-- name: UpdateBarberShopChains :one
UPDATE "BarberShopChains"
SET "name" = coalesce($1, name),
    founder = coalesce($2,founder),
    founding_date = coalesce($3, founding_date),
    website = coalesce($4, website),
    "update_at" = NOW()
WHERE "id" = $5
RETURNING id, name, chain_identifier, founder, founding_date, website
`

type UpdateBarberShopChainsParams struct {
	Name         sql.NullString `json:"name"`
	Founder      sql.NullString `json:"founder"`
	FoundingDate sql.NullTime   `json:"founding_date"`
	Website      sql.NullString `json:"website"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateBarberShopChains(ctx context.Context, arg UpdateBarberShopChainsParams) (BarberShopChain, error) {
	row := q.db.QueryRowContext(ctx, updateBarberShopChains,
		arg.Name,
		arg.Founder,
		arg.FoundingDate,
		arg.Website,
		arg.ID,
	)
	var i BarberShopChain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChainIdentifier,
		&i.Founder,
		&i.FoundingDate,
		&i.Website,
	)
	return i, err
}
