// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Appointment struct {
	ID                  uuid.UUID `json:"id"`
	BarbershopID        uuid.UUID `json:"barbershop_id"`
	CustomerID          uuid.UUID `json:"customer_id"`
	BarberID            uuid.UUID `json:"barber_id"`
	AppointmentDateTime time.Time `json:"appointment_date_time"`
	Status              int32     `json:"status"`
	CreateAt            time.Time `json:"create_at"`
	UpdateAt            time.Time `json:"update_at"`
}

type Barber struct {
	ID                uuid.UUID      `json:"id"`
	GenderID          int32          `json:"gender_id"`
	Email             string         `json:"email"`
	Phone             string         `json:"phone"`
	HashedPassword    string         `json:"hashed_password"`
	NickName          string         `json:"nick_name"`
	FullName          string         `json:"full_name"`
	Haircut           bool           `json:"haircut"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreateAt          time.Time      `json:"create_at"`
	UpdateAt          time.Time      `json:"update_at"`
}

type BarberManager struct {
	BarberID  uuid.UUID `json:"barber_id"`
	ManagerID uuid.UUID `json:"manager_id"`
	CreateAt  time.Time `json:"create_at"`
	UpdateAt  time.Time `json:"update_at"`
}

type BarberReview struct {
	ID         uuid.UUID      `json:"id"`
	BarberID   uuid.UUID      `json:"barber_id"`
	CustomerID uuid.UUID      `json:"customer_id"`
	Rating     int32          `json:"rating"`
	Comment    sql.NullString `json:"comment"`
	CreateAt   time.Time      `json:"create_at"`
	UpdateAt   time.Time      `json:"update_at"`
}

type BarberRole struct {
	ID           uuid.UUID `json:"id"`
	BarberID     uuid.UUID `json:"barber_id"`
	BarbershopID uuid.UUID `json:"barbershop_id"`
	RoleID       int32     `json:"role_id"`
	CreateAt     time.Time `json:"create_at"`
	UpdateAt     time.Time `json:"update_at"`
}

type BarberShop struct {
	ID                uuid.UUID      `json:"id"`
	BarbershopChainID uuid.NullUUID  `json:"barbershop_chain_id"`
	Name              string         `json:"name"`
	IsMainBranch      bool           `json:"is_main_branch"`
	BranchCount       int32          `json:"branch_count"`
	Coordinates       string         `json:"coordinates"`
	Address           string         `json:"address"`
	Image             sql.NullString `json:"image"`
	Status            int32          `json:"status"`
	Rate              float64        `json:"rate"`
	StartTime         pgtype.Time    `json:"start_time"`
	EndTime           pgtype.Time    `json:"end_time"`
	BreakTime         pgtype.Time    `json:"break_time"`
	BreakMinutes      int32          `json:"break_minutes"`
	IntervalScheduler int32          `json:"interval_scheduler"`
	IsReputation      bool           `json:"is_reputation"`
	IsVerified        bool           `json:"is_verified"`
	CreateAt          time.Time      `json:"create_at"`
	UpdateAt          time.Time      `json:"update_at"`
}

type BarberShopChain struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Founder      string         `json:"founder"`
	FoundingDate time.Time      `json:"founding_date"`
	Website      sql.NullString `json:"website"`
	CreateAt     time.Time      `json:"create_at"`
	UpdateAt     time.Time      `json:"update_at"`
}

type BarberShopReview struct {
	ID           uuid.UUID      `json:"id"`
	CustomerID   uuid.UUID      `json:"customer_id"`
	BarbershopID uuid.UUID      `json:"barbershop_id"`
	Rating       int32          `json:"rating"`
	Comment      sql.NullString `json:"comment"`
	CreateAt     time.Time      `json:"create_at"`
	UpdateAt     time.Time      `json:"update_at"`
}

type BarberShopService struct {
	ID                   uuid.UUID      `json:"id"`
	BarbershopCategoryID uuid.UUID      `json:"barbershop_category_id"`
	BarbershopChainID    uuid.NullUUID  `json:"barbershop_chain_id"`
	BarbershopID         uuid.NullUUID  `json:"barbershop_id"`
	GenderID             int32          `json:"gender_id"`
	Name                 string         `json:"name"`
	Timer                int32          `json:"timer"`
	Price                float32        `json:"price"`
	Description          sql.NullString `json:"description"`
	Image                sql.NullString `json:"image"`
	IsCustom             bool           `json:"is_custom"`
	IsRemoved            bool           `json:"is_removed"`
	CreateAt             time.Time      `json:"create_at"`
	UpdateAt             time.Time      `json:"update_at"`
}

type BarberShopServiceCategory struct {
	ID                uuid.UUID     `json:"id"`
	BarbershopChainID uuid.NullUUID `json:"barbershop_chain_id"`
	BarbershopID      uuid.NullUUID `json:"barbershop_id"`
	ServiceCategoryID uuid.UUID     `json:"service_category_id"`
	CreateAt          time.Time     `json:"create_at"`
	UpdateAt          time.Time     `json:"update_at"`
}

type BarberShopServicesAppointment struct {
	BarberShopServicesID  uuid.UUID `json:"BarberShopServices_id"`
	AppointmentsServiceID uuid.UUID `json:"Appointments_service_id"`
}

type Customer struct {
	ID                uuid.UUID      `json:"id"`
	Name              string         `json:"name"`
	Email             string         `json:"email"`
	Phone             sql.NullString `json:"phone"`
	Gender            int32          `json:"gender"`
	HashedPassword    sql.NullString `json:"hashed_password"`
	Avatar            sql.NullString `json:"avatar"`
	IsSocialAuth      sql.NullBool   `json:"is_social_auth"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreateAt          time.Time      `json:"create_at"`
	UpdateAt          time.Time      `json:"update_at"`
}

type Gender struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Role struct {
	ID   int32          `json:"id"`
	Name string         `json:"name"`
	Type sql.NullString `json:"type"`
}

type ServiceCategory struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	IsGlobal bool      `json:"is_global"`
	CreateAt time.Time `json:"create_at"`
	UpdateAt time.Time `json:"update_at"`
}

type SessionsBarber struct {
	ID           uuid.UUID `json:"id"`
	BarberID     uuid.UUID `json:"barber_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	FcmDevice    string    `json:"fcm_device"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreateAt     time.Time `json:"create_at"`
}

type SessionsCustomer struct {
	ID           uuid.UUID   `json:"id"`
	CustomerID   uuid.UUID   `json:"customer_id"`
	RefreshToken string      `json:"refresh_token"`
	UserAgent    string      `json:"user_agent"`
	ClientIp     string      `json:"client_ip"`
	FcmDevice    string      `json:"fcm_device"`
	Timezone     string      `json:"timezone"`
	Coordinates  interface{} `json:"coordinates"`
	IsBlocked    bool        `json:"is_blocked"`
	ExpiresAt    time.Time   `json:"expires_at"`
	CreateAt     time.Time   `json:"create_at"`
}
