// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ChangePasswordCustomer(ctx context.Context, arg ChangePasswordCustomerParams) (Customer, error)
	CreateBarber(ctx context.Context, arg CreateBarberParams) (Barber, error)
	CreateBarberManagers(ctx context.Context, arg CreateBarberManagersParams) (BarberManager, error)
	CreateBarberRoles(ctx context.Context, arg CreateBarberRolesParams) (BarberRole, error)
	CreateBarberShop(ctx context.Context, arg CreateBarberShopParams) (BarberShop, error)
	CreateBarberShopChains(ctx context.Context, arg CreateBarberShopChainsParams) (BarberShopChain, error)
	CreateBarberShopServiceCategoryWithChain(ctx context.Context, arg CreateBarberShopServiceCategoryWithChainParams) (BarberShopServiceCategory, error)
	CreateBarberShopServiceCategoryWithShop(ctx context.Context, arg CreateBarberShopServiceCategoryWithShopParams) (BarberShopServiceCategory, error)
	CreateBarberShopServices(ctx context.Context, arg CreateBarberShopServicesParams) (BarberShopService, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateSessionBarber(ctx context.Context, arg CreateSessionBarberParams) (SessionsBarber, error)
	CreateSessionsCustomer(ctx context.Context, arg CreateSessionsCustomerParams) (SessionsCustomer, error)
	DeleteBarber(ctx context.Context, id uuid.UUID) error
	DeleteBarberManagers(ctx context.Context, arg DeleteBarberManagersParams) error
	DeleteBarberRoles(ctx context.Context, id uuid.UUID) error
	DeleteBarberShopChains(ctx context.Context, id uuid.UUID) error
	DeleteBarberShopServiceCategory(ctx context.Context, id uuid.UUID) error
	DeleteBarberShopServices(ctx context.Context, id uuid.UUID) error
	DeleteBarberShops(ctx context.Context, id uuid.UUID) error
	GetBarber(ctx context.Context, arg GetBarberParams) (GetBarberRow, error)
	GetBarberManagers(ctx context.Context, barberID uuid.NullUUID) (BarberManager, error)
	GetBarberRoles(ctx context.Context, arg GetBarberRolesParams) (GetBarberRolesRow, error)
	GetBarberShop(ctx context.Context, id uuid.UUID) (BarberShop, error)
	GetBarberShopChains(ctx context.Context, id uuid.UUID) (BarberShopChain, error)
	GetContactCustomer(ctx context.Context, arg GetContactCustomerParams) (Customer, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	GetEmailBarber(ctx context.Context, email string) (Barber, error)
	GetSessionBarber(ctx context.Context, id uuid.UUID) (SessionsBarber, error)
	GetSessionsCustomer(ctx context.Context, id uuid.UUID) (SessionsBarber, error)
	InsertAppointmentAndGetInfo(ctx context.Context, arg InsertAppointmentAndGetInfoParams) (InsertAppointmentAndGetInfoRow, error)
	InsertServicesForAppointment(ctx context.Context, arg InsertServicesForAppointmentParams) ([]BarberShopServicesAppointment, error)
	ListAppointmentByDateWithService(ctx context.Context, arg ListAppointmentByDateWithServiceParams) ([]ListAppointmentByDateWithServiceRow, error)
	ListBarberShopServiceCategories(ctx context.Context, arg ListBarberShopServiceCategoriesParams) ([]ListBarberShopServiceCategoriesRow, error)
	ListBarberShopsNearby(ctx context.Context, arg ListBarberShopsNearbyParams) ([]ListBarberShopsNearbyRow, error)
	ListBarbersInBarberShop(ctx context.Context, barbershopID uuid.UUID) ([]ListBarbersInBarberShopRow, error)
	ListBarbersRoles(ctx context.Context, barbershopID uuid.UUID) ([]ListBarbersRolesRow, error)
	QueryBarberShops(ctx context.Context, name string) ([]BarberShop, error)
	UpdateBarber(ctx context.Context, arg UpdateBarberParams) (Barber, error)
	UpdateBarberRoles(ctx context.Context, arg UpdateBarberRolesParams) (BarberRole, error)
	UpdateBarberShop(ctx context.Context, arg UpdateBarberShopParams) (BarberShop, error)
	UpdateBarberShopChains(ctx context.Context, arg UpdateBarberShopChainsParams) (BarberShopChain, error)
	UpdateBarberShopServiceCategory(ctx context.Context, arg UpdateBarberShopServiceCategoryParams) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateSessionRefreshToken(ctx context.Context, arg UpdateSessionRefreshTokenParams) error
	UpdateSessionsCustomer(ctx context.Context, arg UpdateSessionsCustomerParams) error
}

var _ Querier = (*Queries)(nil)
