// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BarberGetIdShop(ctx context.Context, barberID uuid.UUID) (BarberGetIdShopRow, error)
	ChangePasswordCustomer(ctx context.Context, arg ChangePasswordCustomerParams) (Customer, error)
	CreateBarber(ctx context.Context, arg CreateBarberParams) (Barber, error)
	CreateBarberShops(ctx context.Context, arg CreateBarberShopsParams) (BarberShop, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateServicesCategoryPrivate(ctx context.Context, arg CreateServicesCategoryPrivateParams) (ServiceCategory, error)
	CreateServicesCategoryPublic(ctx context.Context, arg CreateServicesCategoryPublicParams) (ServiceCategory, error)
	CreateServicesPrivate(ctx context.Context, arg CreateServicesPrivateParams) (Service, error)
	CreateServicesPublic(ctx context.Context, arg CreateServicesPublicParams) (Service, error)
	CreateSessionBarber(ctx context.Context, arg CreateSessionBarberParams) (SessionsBarber, error)
	CreateSessionsCustomer(ctx context.Context, arg CreateSessionsCustomerParams) (SessionsCustomer, error)
	FindBarberShopNearbyLocations(ctx context.Context, arg FindBarberShopNearbyLocationsParams) ([]FindBarberShopNearbyLocationsRow, error)
	GetAppointmentByDate(ctx context.Context, arg GetAppointmentByDateParams) ([]Appointment, error)
	GetBarberInBarberShop(ctx context.Context, shopID uuid.NullUUID) ([]Barber, error)
	GetBarberShop(ctx context.Context, shopID uuid.UUID) (uuid.UUID, error)
	GetContactCustomer(ctx context.Context, arg GetContactCustomerParams) (Customer, error)
	GetCustomer(ctx context.Context, customerID uuid.UUID) (Customer, error)
	GetEmailBarber(ctx context.Context, email string) (Barber, error)
	GetSessionsBarber(ctx context.Context, id uuid.UUID) (SessionsBarber, error)
	GetSessionsCustomer(ctx context.Context, id uuid.UUID) (SessionsCustomer, error)
	InsertAppointment(ctx context.Context, arg InsertAppointmentParams) (Appointment, error)
	InsertServicesForAppointment(ctx context.Context, arg InsertServicesForAppointmentParams) ([]InsertServicesForAppointmentRow, error)
	UpdateBarber(ctx context.Context, arg UpdateBarberParams) (Barber, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateRefreshTokenSessionsBarber(ctx context.Context, arg UpdateRefreshTokenSessionsBarberParams) (SessionsBarber, error)
	UpdateRefreshTokenSessionsCustomer(ctx context.Context, arg UpdateRefreshTokenSessionsCustomerParams) (SessionsCustomer, error)
	UpdateServicesCategoryPublicSeparate(ctx context.Context, arg UpdateServicesCategoryPublicSeparateParams) (ServiceCategory, error)
	UpdateServicesPublicSeparate(ctx context.Context, arg UpdateServicesPublicSeparateParams) (Service, error)
}

var _ Querier = (*Queries)(nil)
