// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: sessions_customers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSessionsCustomer = `-- name: CreateSessionsCustomer :one
INSERT INTO "SessionsCustomer" (
                               customer_id,
                               refresh_token,
                               user_agent,
                               client_ip,
                               fcm_device,
                               is_blocked,
                               expires_at,
                               coordinates
                               )
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        now() + interval '30 minutes',
        ST_GeographyFromText('POINT(' || $7::float8 || ' ' || $8::float8 || ')')
        ) RETURNING id, customer_id, refresh_token, user_agent, client_ip, fcm_device, coordinates, is_blocked, expires_at, create_at
`

type CreateSessionsCustomerParams struct {
	CustomerID   uuid.UUID `json:"customer_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	FcmDevice    string    `json:"fcm_device"`
	IsBlocked    bool      `json:"is_blocked"`
	Longitude    float64   `json:"longitude"`
	Latitude     float64   `json:"latitude"`
}

func (q *Queries) CreateSessionsCustomer(ctx context.Context, arg CreateSessionsCustomerParams) (SessionsCustomer, error) {
	row := q.db.QueryRow(ctx, createSessionsCustomer,
		arg.CustomerID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.FcmDevice,
		arg.IsBlocked,
		arg.Longitude,
		arg.Latitude,
	)
	var i SessionsCustomer
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.FcmDevice,
		&i.Coordinates,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreateAt,
	)
	return i, err
}

const getSessionsCustomer = `-- name: GetSessionsCustomer :one
SELECT id, customer_id, refresh_token, user_agent, client_ip, fcm_device, coordinates, is_blocked, expires_at, create_at
FROM "SessionsCustomer"
WHERE id = $1
`

func (q *Queries) GetSessionsCustomer(ctx context.Context, id uuid.UUID) (SessionsCustomer, error) {
	row := q.db.QueryRow(ctx, getSessionsCustomer, id)
	var i SessionsCustomer
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.FcmDevice,
		&i.Coordinates,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreateAt,
	)
	return i, err
}

const updateSessionsCustomer = `-- name: UpdateSessionsCustomer :exec
UPDATE "SessionsCustomer"
SET refresh_token = $2,
 "expires_at" = now() + interval '30 minutes'
WHERE id = $1
RETURNING id, customer_id, refresh_token, user_agent, client_ip, fcm_device, coordinates, is_blocked, expires_at, create_at
`

type UpdateSessionsCustomerParams struct {
	ID           uuid.UUID `json:"id"`
	RefreshToken string    `json:"refresh_token"`
}

func (q *Queries) UpdateSessionsCustomer(ctx context.Context, arg UpdateSessionsCustomerParams) error {
	_, err := q.db.Exec(ctx, updateSessionsCustomer, arg.ID, arg.RefreshToken)
	return err
}
