// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: rpc_create_barbershop.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBarberShopsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodeBarberShop string `protobuf:"bytes,1,opt,name=code_barber_shop,json=codeBarberShop,proto3" json:"code_barber_shop,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location       uint32 `protobuf:"fixed32,3,opt,name=location,proto3" json:"location,omitempty"`
	Address        string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CreateBarberShopsRequest) Reset() {
	*x = CreateBarberShopsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_barbershop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBarberShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarberShopsRequest) ProtoMessage() {}

func (x *CreateBarberShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_barbershop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarberShopsRequest.ProtoReflect.Descriptor instead.
func (*CreateBarberShopsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_barbershop_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBarberShopsRequest) GetCodeBarberShop() string {
	if x != nil {
		return x.CodeBarberShop
	}
	return ""
}

func (x *CreateBarberShopsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBarberShopsRequest) GetLocation() uint32 {
	if x != nil {
		return x.Location
	}
	return 0
}

func (x *CreateBarberShopsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateBarberShopsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarberShop *BarberShops `protobuf:"bytes,1,opt,name=barber_shop,json=barberShop,proto3" json:"barber_shop,omitempty"`
}

func (x *CreateBarberShopsResponse) Reset() {
	*x = CreateBarberShopsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_barbershop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBarberShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarberShopsResponse) ProtoMessage() {}

func (x *CreateBarberShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_barbershop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarberShopsResponse.ProtoReflect.Descriptor instead.
func (*CreateBarberShopsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_barbershop_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBarberShopsResponse) GetBarberShop() *BarberShops {
	if x != nil {
		return x.BarberShop
	}
	return nil
}

var File_rpc_create_barbershop_proto protoreflect.FileDescriptor

var file_rpc_create_barbershop_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x12, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x62, 0x61, 0x72, 0x62, 0x65,
	0x72, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x64, 0x65, 0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4d, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x68,
	0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61,
	0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x52, 0x0a, 0x62, 0x61, 0x72, 0x62, 0x65,
	0x72, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x13, 0x5a, 0x11, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x6f, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rpc_create_barbershop_proto_rawDescOnce sync.Once
	file_rpc_create_barbershop_proto_rawDescData = file_rpc_create_barbershop_proto_rawDesc
)

func file_rpc_create_barbershop_proto_rawDescGZIP() []byte {
	file_rpc_create_barbershop_proto_rawDescOnce.Do(func() {
		file_rpc_create_barbershop_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_barbershop_proto_rawDescData)
	})
	return file_rpc_create_barbershop_proto_rawDescData
}

var file_rpc_create_barbershop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_barbershop_proto_goTypes = []interface{}{
	(*CreateBarberShopsRequest)(nil),  // 0: pb.CreateBarberShopsRequest
	(*CreateBarberShopsResponse)(nil), // 1: pb.CreateBarberShopsResponse
	(*BarberShops)(nil),               // 2: pb.BarberShops
}
var file_rpc_create_barbershop_proto_depIdxs = []int32{
	2, // 0: pb.CreateBarberShopsResponse.barber_shop:type_name -> pb.BarberShops
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_barbershop_proto_init() }
func file_rpc_create_barbershop_proto_init() {
	if File_rpc_create_barbershop_proto != nil {
		return
	}
	file_barber_shops_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_barbershop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBarberShopsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_barbershop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBarberShopsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_barbershop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_barbershop_proto_goTypes,
		DependencyIndexes: file_rpc_create_barbershop_proto_depIdxs,
		MessageInfos:      file_rpc_create_barbershop_proto_msgTypes,
	}.Build()
	File_rpc_create_barbershop_proto = out.File
	file_rpc_create_barbershop_proto_rawDesc = nil
	file_rpc_create_barbershop_proto_goTypes = nil
	file_rpc_create_barbershop_proto_depIdxs = nil
}
