-- name: CreateBarberShopServices :one
-- INSERT INTO "BarberShopServices" (
--     category_id
--   )
-- VALUES ($1)
-- RETURNING *;

-- -- name: DeleteBarberShopServices :exec
-- DELETE FROM "BarberShopServices"
-- WHERE
--   "id" = $1;