// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: barber/rpc_create_service_category.proto

package barber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateServicesCategoryPrivateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarberShopId string `protobuf:"bytes,1,opt,name=barber_shop_id,json=barberShopId,proto3" json:"barber_shop_id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateServicesCategoryPrivateRequest) Reset() {
	*x = CreateServicesCategoryPrivateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_create_service_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServicesCategoryPrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServicesCategoryPrivateRequest) ProtoMessage() {}

func (x *CreateServicesCategoryPrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_create_service_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServicesCategoryPrivateRequest.ProtoReflect.Descriptor instead.
func (*CreateServicesCategoryPrivateRequest) Descriptor() ([]byte, []int) {
	return file_barber_rpc_create_service_category_proto_rawDescGZIP(), []int{0}
}

func (x *CreateServicesCategoryPrivateRequest) GetBarberShopId() string {
	if x != nil {
		return x.BarberShopId
	}
	return ""
}

func (x *CreateServicesCategoryPrivateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateServicesCategoryPublicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateServicesCategoryPublicRequest) Reset() {
	*x = CreateServicesCategoryPublicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_create_service_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServicesCategoryPublicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServicesCategoryPublicRequest) ProtoMessage() {}

func (x *CreateServicesCategoryPublicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_create_service_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServicesCategoryPublicRequest.ProtoReflect.Descriptor instead.
func (*CreateServicesCategoryPublicRequest) Descriptor() ([]byte, []int) {
	return file_barber_rpc_create_service_category_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServicesCategoryPublicRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CreateServicesCategoryPublicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateServicesCategoryPublicSeparateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId      string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BarberShopId string `protobuf:"bytes,2,opt,name=barber_shop_id,json=barberShopId,proto3" json:"barber_shop_id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateServicesCategoryPublicSeparateRequest) Reset() {
	*x = UpdateServicesCategoryPublicSeparateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_create_service_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServicesCategoryPublicSeparateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServicesCategoryPublicSeparateRequest) ProtoMessage() {}

func (x *UpdateServicesCategoryPublicSeparateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_create_service_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServicesCategoryPublicSeparateRequest.ProtoReflect.Descriptor instead.
func (*UpdateServicesCategoryPublicSeparateRequest) Descriptor() ([]byte, []int) {
	return file_barber_rpc_create_service_category_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateServicesCategoryPublicSeparateRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *UpdateServicesCategoryPublicSeparateRequest) GetBarberShopId() string {
	if x != nil {
		return x.BarberShopId
	}
	return ""
}

func (x *UpdateServicesCategoryPublicSeparateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateServicesCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Barber *ServiceCategory `protobuf:"bytes,1,opt,name=barber,proto3" json:"barber,omitempty"`
}

func (x *CreateServicesCategoryResponse) Reset() {
	*x = CreateServicesCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_create_service_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServicesCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServicesCategoryResponse) ProtoMessage() {}

func (x *CreateServicesCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_create_service_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServicesCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateServicesCategoryResponse) Descriptor() ([]byte, []int) {
	return file_barber_rpc_create_service_category_proto_rawDescGZIP(), []int{3}
}

func (x *CreateServicesCategoryResponse) GetBarber() *ServiceCategory {
	if x != nil {
		return x.Barber
	}
	return nil
}

var File_barber_rpc_create_service_category_proto protoreflect.FileDescriptor

var file_barber_rpc_create_service_category_proto_rawDesc = []byte{
	0x0a, 0x28, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1d,
	0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a,
	0x24, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f,
	0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62,
	0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x54, 0x0a, 0x23, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x2b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x53, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72,
	0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x1e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06,
	0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x06, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x62,
	0x61, 0x72, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_barber_rpc_create_service_category_proto_rawDescOnce sync.Once
	file_barber_rpc_create_service_category_proto_rawDescData = file_barber_rpc_create_service_category_proto_rawDesc
)

func file_barber_rpc_create_service_category_proto_rawDescGZIP() []byte {
	file_barber_rpc_create_service_category_proto_rawDescOnce.Do(func() {
		file_barber_rpc_create_service_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_barber_rpc_create_service_category_proto_rawDescData)
	})
	return file_barber_rpc_create_service_category_proto_rawDescData
}

var file_barber_rpc_create_service_category_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_barber_rpc_create_service_category_proto_goTypes = []interface{}{
	(*CreateServicesCategoryPrivateRequest)(nil),        // 0: pb.CreateServicesCategoryPrivateRequest
	(*CreateServicesCategoryPublicRequest)(nil),         // 1: pb.CreateServicesCategoryPublicRequest
	(*UpdateServicesCategoryPublicSeparateRequest)(nil), // 2: pb.UpdateServicesCategoryPublicSeparateRequest
	(*CreateServicesCategoryResponse)(nil),              // 3: pb.CreateServicesCategoryResponse
	(*ServiceCategory)(nil),                             // 4: pb.ServiceCategory
}
var file_barber_rpc_create_service_category_proto_depIdxs = []int32{
	4, // 0: pb.CreateServicesCategoryResponse.barber:type_name -> pb.ServiceCategory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_barber_rpc_create_service_category_proto_init() }
func file_barber_rpc_create_service_category_proto_init() {
	if File_barber_rpc_create_service_category_proto != nil {
		return
	}
	file_barber_service_category_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_barber_rpc_create_service_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServicesCategoryPrivateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barber_rpc_create_service_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServicesCategoryPublicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barber_rpc_create_service_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServicesCategoryPublicSeparateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barber_rpc_create_service_category_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServicesCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_barber_rpc_create_service_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_barber_rpc_create_service_category_proto_goTypes,
		DependencyIndexes: file_barber_rpc_create_service_category_proto_depIdxs,
		MessageInfos:      file_barber_rpc_create_service_category_proto_msgTypes,
	}.Build()
	File_barber_rpc_create_service_category_proto = out.File
	file_barber_rpc_create_service_category_proto_rawDesc = nil
	file_barber_rpc_create_service_category_proto_goTypes = nil
	file_barber_rpc_create_service_category_proto_depIdxs = nil
}
