// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: barber/rpc_barbershop_chains_update.proto

package barber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateBarberShopChainsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description  *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Founder      *string                `protobuf:"bytes,4,opt,name=founder,proto3,oneof" json:"founder,omitempty"`
	FoundingDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=founding_date,json=foundingDate,proto3,oneof" json:"founding_date,omitempty"`
	Website      *string                `protobuf:"bytes,6,opt,name=website,proto3,oneof" json:"website,omitempty"`
}

func (x *UpdateBarberShopChainsRequest) Reset() {
	*x = UpdateBarberShopChainsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_barbershop_chains_update_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBarberShopChainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBarberShopChainsRequest) ProtoMessage() {}

func (x *UpdateBarberShopChainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_barbershop_chains_update_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBarberShopChainsRequest.ProtoReflect.Descriptor instead.
func (*UpdateBarberShopChainsRequest) Descriptor() ([]byte, []int) {
	return file_barber_rpc_barbershop_chains_update_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateBarberShopChainsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBarberShopChainsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateBarberShopChainsRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateBarberShopChainsRequest) GetFounder() string {
	if x != nil && x.Founder != nil {
		return *x.Founder
	}
	return ""
}

func (x *UpdateBarberShopChainsRequest) GetFoundingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FoundingDate
	}
	return nil
}

func (x *UpdateBarberShopChainsRequest) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

type UpdateBarberShopChainsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarbershopChain *BarberShopChains `protobuf:"bytes,1,opt,name=barbershop_chain,json=barbershopChain,proto3" json:"barbershop_chain,omitempty"`
}

func (x *UpdateBarberShopChainsResponse) Reset() {
	*x = UpdateBarberShopChainsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_barbershop_chains_update_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBarberShopChainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBarberShopChainsResponse) ProtoMessage() {}

func (x *UpdateBarberShopChainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_barbershop_chains_update_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBarberShopChainsResponse.ProtoReflect.Descriptor instead.
func (*UpdateBarberShopChainsResponse) Descriptor() ([]byte, []int) {
	return file_barber_rpc_barbershop_chains_update_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBarberShopChainsResponse) GetBarbershopChain() *BarberShopChains {
	if x != nil {
		return x.BarbershopChain
	}
	return nil
}

var File_barber_rpc_barbershop_chains_update_proto protoreflect.FileDescriptor

var file_barber_rpc_barbershop_chains_update_proto_rawDesc = []byte{
	0x0a, 0x29, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x5f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb6, 0x02, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x72, 0x62, 0x65,
	0x72, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x12, 0x44, 0x0a, 0x0d, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x48, 0x03, 0x52, 0x0c, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x44, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x07, 0x77, 0x65, 0x62, 0x73,
	0x69, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x10, 0x0a, 0x0e, 0x5f,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x22, 0x61, 0x0a, 0x1e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x62,
	0x61, 0x72, 0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x72, 0x62, 0x65,
	0x72, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x52, 0x0f, 0x62, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x1a, 0x5a, 0x18,
	0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70,
	0x62, 0x2f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_barber_rpc_barbershop_chains_update_proto_rawDescOnce sync.Once
	file_barber_rpc_barbershop_chains_update_proto_rawDescData = file_barber_rpc_barbershop_chains_update_proto_rawDesc
)

func file_barber_rpc_barbershop_chains_update_proto_rawDescGZIP() []byte {
	file_barber_rpc_barbershop_chains_update_proto_rawDescOnce.Do(func() {
		file_barber_rpc_barbershop_chains_update_proto_rawDescData = protoimpl.X.CompressGZIP(file_barber_rpc_barbershop_chains_update_proto_rawDescData)
	})
	return file_barber_rpc_barbershop_chains_update_proto_rawDescData
}

var file_barber_rpc_barbershop_chains_update_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_barber_rpc_barbershop_chains_update_proto_goTypes = []interface{}{
	(*UpdateBarberShopChainsRequest)(nil),  // 0: pb.UpdateBarberShopChainsRequest
	(*UpdateBarberShopChainsResponse)(nil), // 1: pb.UpdateBarberShopChainsResponse
	(*timestamppb.Timestamp)(nil),          // 2: google.protobuf.Timestamp
	(*BarberShopChains)(nil),               // 3: pb.BarberShopChains
}
var file_barber_rpc_barbershop_chains_update_proto_depIdxs = []int32{
	2, // 0: pb.UpdateBarberShopChainsRequest.founding_date:type_name -> google.protobuf.Timestamp
	3, // 1: pb.UpdateBarberShopChainsResponse.barbershop_chain:type_name -> pb.BarberShopChains
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_barber_rpc_barbershop_chains_update_proto_init() }
func file_barber_rpc_barbershop_chains_update_proto_init() {
	if File_barber_rpc_barbershop_chains_update_proto != nil {
		return
	}
	file_barber_barbershop_chains_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_barber_rpc_barbershop_chains_update_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBarberShopChainsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barber_rpc_barbershop_chains_update_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBarberShopChainsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_barber_rpc_barbershop_chains_update_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_barber_rpc_barbershop_chains_update_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_barber_rpc_barbershop_chains_update_proto_goTypes,
		DependencyIndexes: file_barber_rpc_barbershop_chains_update_proto_depIdxs,
		MessageInfos:      file_barber_rpc_barbershop_chains_update_proto_msgTypes,
	}.Build()
	File_barber_rpc_barbershop_chains_update_proto = out.File
	file_barber_rpc_barbershop_chains_update_proto_rawDesc = nil
	file_barber_rpc_barbershop_chains_update_proto_goTypes = nil
	file_barber_rpc_barbershop_chains_update_proto_depIdxs = nil
}
