// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: barber/rpc_find_barbershops_nearby.proto

package barber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindBarberShopsNearbyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude        *wrapperspb.DoubleValue `protobuf:"bytes,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude         *wrapperspb.DoubleValue `protobuf:"bytes,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	DistanceInMeters int32                   `protobuf:"varint,3,opt,name=distance_in_meters,json=distanceInMeters,proto3" json:"distance_in_meters,omitempty"`
}

func (x *FindBarberShopsNearbyRequest) Reset() {
	*x = FindBarberShopsNearbyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_find_barbershops_nearby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBarberShopsNearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBarberShopsNearbyRequest) ProtoMessage() {}

func (x *FindBarberShopsNearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_find_barbershops_nearby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBarberShopsNearbyRequest.ProtoReflect.Descriptor instead.
func (*FindBarberShopsNearbyRequest) Descriptor() ([]byte, []int) {
	return file_barber_rpc_find_barbershops_nearby_proto_rawDescGZIP(), []int{0}
}

func (x *FindBarberShopsNearbyRequest) GetLongitude() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Longitude
	}
	return nil
}

func (x *FindBarberShopsNearbyRequest) GetLatitude() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Latitude
	}
	return nil
}

func (x *FindBarberShopsNearbyRequest) GetDistanceInMeters() int32 {
	if x != nil {
		return x.DistanceInMeters
	}
	return 0
}

type FindBarberShopsNearbyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarberShops []*BarberShop `protobuf:"bytes,1,rep,name=barber_shops,json=barberShops,proto3" json:"barber_shops,omitempty"`
}

func (x *FindBarberShopsNearbyResponse) Reset() {
	*x = FindBarberShopsNearbyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_find_barbershops_nearby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindBarberShopsNearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBarberShopsNearbyResponse) ProtoMessage() {}

func (x *FindBarberShopsNearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_find_barbershops_nearby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBarberShopsNearbyResponse.ProtoReflect.Descriptor instead.
func (*FindBarberShopsNearbyResponse) Descriptor() ([]byte, []int) {
	return file_barber_rpc_find_barbershops_nearby_proto_rawDescGZIP(), []int{1}
}

func (x *FindBarberShopsNearbyResponse) GetBarberShops() []*BarberShop {
	if x != nil {
		return x.BarberShops
	}
	return nil
}

var File_barber_rpc_find_barbershops_nearby_proto protoreflect.FileDescriptor

var file_barber_rpc_find_barbershops_nearby_proto_rawDesc = []byte{
	0x0a, 0x28, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x69, 0x6e,
	0x64, 0x5f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x5f, 0x6e, 0x65,
	0x61, 0x72, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x18,
	0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x68,
	0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x01, 0x0a, 0x1c, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x73, 0x4e, 0x65, 0x61, 0x72,
	0x62, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x52, 0x0a,
	0x1d, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x73,
	0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x0c, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x72, 0x62, 0x65, 0x72,
	0x53, 0x68, 0x6f, 0x70, 0x52, 0x0b, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70,
	0x73, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_barber_rpc_find_barbershops_nearby_proto_rawDescOnce sync.Once
	file_barber_rpc_find_barbershops_nearby_proto_rawDescData = file_barber_rpc_find_barbershops_nearby_proto_rawDesc
)

func file_barber_rpc_find_barbershops_nearby_proto_rawDescGZIP() []byte {
	file_barber_rpc_find_barbershops_nearby_proto_rawDescOnce.Do(func() {
		file_barber_rpc_find_barbershops_nearby_proto_rawDescData = protoimpl.X.CompressGZIP(file_barber_rpc_find_barbershops_nearby_proto_rawDescData)
	})
	return file_barber_rpc_find_barbershops_nearby_proto_rawDescData
}

var file_barber_rpc_find_barbershops_nearby_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_barber_rpc_find_barbershops_nearby_proto_goTypes = []interface{}{
	(*FindBarberShopsNearbyRequest)(nil),  // 0: pb.FindBarberShopsNearbyRequest
	(*FindBarberShopsNearbyResponse)(nil), // 1: pb.FindBarberShopsNearbyResponse
	(*wrapperspb.DoubleValue)(nil),        // 2: google.protobuf.DoubleValue
	(*BarberShop)(nil),                    // 3: pb.BarberShop
}
var file_barber_rpc_find_barbershops_nearby_proto_depIdxs = []int32{
	2, // 0: pb.FindBarberShopsNearbyRequest.longitude:type_name -> google.protobuf.DoubleValue
	2, // 1: pb.FindBarberShopsNearbyRequest.latitude:type_name -> google.protobuf.DoubleValue
	3, // 2: pb.FindBarberShopsNearbyResponse.barber_shops:type_name -> pb.BarberShop
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_barber_rpc_find_barbershops_nearby_proto_init() }
func file_barber_rpc_find_barbershops_nearby_proto_init() {
	if File_barber_rpc_find_barbershops_nearby_proto != nil {
		return
	}
	file_barber_barber_shop_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_barber_rpc_find_barbershops_nearby_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBarberShopsNearbyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barber_rpc_find_barbershops_nearby_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindBarberShopsNearbyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_barber_rpc_find_barbershops_nearby_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_barber_rpc_find_barbershops_nearby_proto_goTypes,
		DependencyIndexes: file_barber_rpc_find_barbershops_nearby_proto_depIdxs,
		MessageInfos:      file_barber_rpc_find_barbershops_nearby_proto_msgTypes,
	}.Build()
	File_barber_rpc_find_barbershops_nearby_proto = out.File
	file_barber_rpc_find_barbershops_nearby_proto_rawDesc = nil
	file_barber_rpc_find_barbershops_nearby_proto_goTypes = nil
	file_barber_rpc_find_barbershops_nearby_proto_depIdxs = nil
}
