// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: barber/rpc_barbershop_service_categories_create.proto

package barber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBarberShopServiceCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarberShopChainId *string `protobuf:"bytes,1,opt,name=barber_shop_chain_id,json=barberShopChainId,proto3,oneof" json:"barber_shop_chain_id,omitempty"`
	BarberShopId      *string `protobuf:"bytes,2,opt,name=barber_shop_id,json=barberShopId,proto3,oneof" json:"barber_shop_id,omitempty"`
	ServiceCategoryId string  `protobuf:"bytes,3,opt,name=service_category_id,json=serviceCategoryId,proto3" json:"service_category_id,omitempty"`
}

func (x *CreateBarberShopServiceCategoriesRequest) Reset() {
	*x = CreateBarberShopServiceCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_barbershop_service_categories_create_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBarberShopServiceCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarberShopServiceCategoriesRequest) ProtoMessage() {}

func (x *CreateBarberShopServiceCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_barbershop_service_categories_create_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarberShopServiceCategoriesRequest.ProtoReflect.Descriptor instead.
func (*CreateBarberShopServiceCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_barber_rpc_barbershop_service_categories_create_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBarberShopServiceCategoriesRequest) GetBarberShopChainId() string {
	if x != nil && x.BarberShopChainId != nil {
		return *x.BarberShopChainId
	}
	return ""
}

func (x *CreateBarberShopServiceCategoriesRequest) GetBarberShopId() string {
	if x != nil && x.BarberShopId != nil {
		return *x.BarberShopId
	}
	return ""
}

func (x *CreateBarberShopServiceCategoriesRequest) GetServiceCategoryId() string {
	if x != nil {
		return x.ServiceCategoryId
	}
	return ""
}

type CreateBarberShopServiceCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceCategory *BarberShopServiceCategories `protobuf:"bytes,1,opt,name=service_category,json=serviceCategory,proto3" json:"service_category,omitempty"`
}

func (x *CreateBarberShopServiceCategoriesResponse) Reset() {
	*x = CreateBarberShopServiceCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_barbershop_service_categories_create_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBarberShopServiceCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarberShopServiceCategoriesResponse) ProtoMessage() {}

func (x *CreateBarberShopServiceCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_barbershop_service_categories_create_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarberShopServiceCategoriesResponse.ProtoReflect.Descriptor instead.
func (*CreateBarberShopServiceCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_barber_rpc_barbershop_service_categories_create_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBarberShopServiceCategoriesResponse) GetServiceCategory() *BarberShopServiceCategories {
	if x != nil {
		return x.ServiceCategory
	}
	return nil
}

var File_barber_rpc_barbershop_service_categories_create_proto protoreflect.FileDescriptor

var file_barber_rpc_barbershop_service_categories_create_proto_rawDesc = []byte{
	0x0a, 0x35, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x2a, 0x62, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x28, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x14, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x11, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0e, 0x62, 0x61,
	0x72, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0c, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72,
	0x5f, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x42, 0x11,
	0x0a, 0x0f, 0x5f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69,
	0x64, 0x22, 0x77, 0x0a, 0x29, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x72, 0x62, 0x65,
	0x72, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a,
	0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61,
	0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x61,
	0x72, 0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x2f,
	0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_barber_rpc_barbershop_service_categories_create_proto_rawDescOnce sync.Once
	file_barber_rpc_barbershop_service_categories_create_proto_rawDescData = file_barber_rpc_barbershop_service_categories_create_proto_rawDesc
)

func file_barber_rpc_barbershop_service_categories_create_proto_rawDescGZIP() []byte {
	file_barber_rpc_barbershop_service_categories_create_proto_rawDescOnce.Do(func() {
		file_barber_rpc_barbershop_service_categories_create_proto_rawDescData = protoimpl.X.CompressGZIP(file_barber_rpc_barbershop_service_categories_create_proto_rawDescData)
	})
	return file_barber_rpc_barbershop_service_categories_create_proto_rawDescData
}

var file_barber_rpc_barbershop_service_categories_create_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_barber_rpc_barbershop_service_categories_create_proto_goTypes = []interface{}{
	(*CreateBarberShopServiceCategoriesRequest)(nil),  // 0: pb.CreateBarberShopServiceCategoriesRequest
	(*CreateBarberShopServiceCategoriesResponse)(nil), // 1: pb.CreateBarberShopServiceCategoriesResponse
	(*BarberShopServiceCategories)(nil),               // 2: pb.BarberShopServiceCategories
}
var file_barber_rpc_barbershop_service_categories_create_proto_depIdxs = []int32{
	2, // 0: pb.CreateBarberShopServiceCategoriesResponse.service_category:type_name -> pb.BarberShopServiceCategories
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_barber_rpc_barbershop_service_categories_create_proto_init() }
func file_barber_rpc_barbershop_service_categories_create_proto_init() {
	if File_barber_rpc_barbershop_service_categories_create_proto != nil {
		return
	}
	file_barber_barbershop_service_categories_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_barber_rpc_barbershop_service_categories_create_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBarberShopServiceCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barber_rpc_barbershop_service_categories_create_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBarberShopServiceCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_barber_rpc_barbershop_service_categories_create_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_barber_rpc_barbershop_service_categories_create_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_barber_rpc_barbershop_service_categories_create_proto_goTypes,
		DependencyIndexes: file_barber_rpc_barbershop_service_categories_create_proto_depIdxs,
		MessageInfos:      file_barber_rpc_barbershop_service_categories_create_proto_msgTypes,
	}.Build()
	File_barber_rpc_barbershop_service_categories_create_proto = out.File
	file_barber_rpc_barbershop_service_categories_create_proto_rawDesc = nil
	file_barber_rpc_barbershop_service_categories_create_proto_goTypes = nil
	file_barber_rpc_barbershop_service_categories_create_proto_depIdxs = nil
}
