// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: barber/rpc_barbershop_services_lookup.proto

package barber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupBarberShopServicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarberShopId string `protobuf:"bytes,1,opt,name=barber_shop_id,json=barberShopId,proto3" json:"barber_shop_id,omitempty"`
}

func (x *LookupBarberShopServicesRequest) Reset() {
	*x = LookupBarberShopServicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_barbershop_services_lookup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupBarberShopServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupBarberShopServicesRequest) ProtoMessage() {}

func (x *LookupBarberShopServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_barbershop_services_lookup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupBarberShopServicesRequest.ProtoReflect.Descriptor instead.
func (*LookupBarberShopServicesRequest) Descriptor() ([]byte, []int) {
	return file_barber_rpc_barbershop_services_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *LookupBarberShopServicesRequest) GetBarberShopId() string {
	if x != nil {
		return x.BarberShopId
	}
	return ""
}

type LookupBarberShopServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarbershopServices []*LookupItemBarberShopService `protobuf:"bytes,1,rep,name=barbershop_services,json=barbershopServices,proto3" json:"barbershop_services,omitempty"`
}

func (x *LookupBarberShopServicesResponse) Reset() {
	*x = LookupBarberShopServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_barbershop_services_lookup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupBarberShopServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupBarberShopServicesResponse) ProtoMessage() {}

func (x *LookupBarberShopServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_barbershop_services_lookup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupBarberShopServicesResponse.ProtoReflect.Descriptor instead.
func (*LookupBarberShopServicesResponse) Descriptor() ([]byte, []int) {
	return file_barber_rpc_barbershop_services_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *LookupBarberShopServicesResponse) GetBarbershopServices() []*LookupItemBarberShopService {
	if x != nil {
		return x.BarbershopServices
	}
	return nil
}

type LookupItemBarberShopService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId int32  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LookupItemBarberShopService) Reset() {
	*x = LookupItemBarberShopService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_barber_rpc_barbershop_services_lookup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupItemBarberShopService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupItemBarberShopService) ProtoMessage() {}

func (x *LookupItemBarberShopService) ProtoReflect() protoreflect.Message {
	mi := &file_barber_rpc_barbershop_services_lookup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupItemBarberShopService.ProtoReflect.Descriptor instead.
func (*LookupItemBarberShopService) Descriptor() ([]byte, []int) {
	return file_barber_rpc_barbershop_services_lookup_proto_rawDescGZIP(), []int{2}
}

func (x *LookupItemBarberShopService) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LookupItemBarberShopService) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *LookupItemBarberShopService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_barber_rpc_barbershop_services_lookup_proto protoreflect.FileDescriptor

var file_barber_rpc_barbershop_services_lookup_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x5f, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x20, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x2f, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x6f, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x1f, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x42, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72,
	0x5f, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x20,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x13, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x61, 0x72,
	0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x12,
	0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x22, 0x62, 0x0a, 0x1b, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d,
	0x42, 0x61, 0x72, 0x62, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x6f, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x61, 0x72, 0x62,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_barber_rpc_barbershop_services_lookup_proto_rawDescOnce sync.Once
	file_barber_rpc_barbershop_services_lookup_proto_rawDescData = file_barber_rpc_barbershop_services_lookup_proto_rawDesc
)

func file_barber_rpc_barbershop_services_lookup_proto_rawDescGZIP() []byte {
	file_barber_rpc_barbershop_services_lookup_proto_rawDescOnce.Do(func() {
		file_barber_rpc_barbershop_services_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(file_barber_rpc_barbershop_services_lookup_proto_rawDescData)
	})
	return file_barber_rpc_barbershop_services_lookup_proto_rawDescData
}

var file_barber_rpc_barbershop_services_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_barber_rpc_barbershop_services_lookup_proto_goTypes = []interface{}{
	(*LookupBarberShopServicesRequest)(nil),  // 0: pb.LookupBarberShopServicesRequest
	(*LookupBarberShopServicesResponse)(nil), // 1: pb.LookupBarberShopServicesResponse
	(*LookupItemBarberShopService)(nil),      // 2: pb.LookupItemBarberShopService
}
var file_barber_rpc_barbershop_services_lookup_proto_depIdxs = []int32{
	2, // 0: pb.LookupBarberShopServicesResponse.barbershop_services:type_name -> pb.LookupItemBarberShopService
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_barber_rpc_barbershop_services_lookup_proto_init() }
func file_barber_rpc_barbershop_services_lookup_proto_init() {
	if File_barber_rpc_barbershop_services_lookup_proto != nil {
		return
	}
	file_barber_barbershop_services_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_barber_rpc_barbershop_services_lookup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupBarberShopServicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barber_rpc_barbershop_services_lookup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupBarberShopServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_barber_rpc_barbershop_services_lookup_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupItemBarberShopService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_barber_rpc_barbershop_services_lookup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_barber_rpc_barbershop_services_lookup_proto_goTypes,
		DependencyIndexes: file_barber_rpc_barbershop_services_lookup_proto_depIdxs,
		MessageInfos:      file_barber_rpc_barbershop_services_lookup_proto_msgTypes,
	}.Build()
	File_barber_rpc_barbershop_services_lookup_proto = out.File
	file_barber_rpc_barbershop_services_lookup_proto_rawDesc = nil
	file_barber_rpc_barbershop_services_lookup_proto_goTypes = nil
	file_barber_rpc_barbershop_services_lookup_proto_depIdxs = nil
}
