DROP TABLE IF EXISTS "Services_Appointments";
DROP TABLE IF EXISTS "Appointments";
DROP TABLE IF EXISTS "SessionsCustomers";
DROP TABLE IF EXISTS "Customers";
DROP TABLE IF EXISTS "Services";
DROP TABLE IF EXISTS "ServiceCategories";
DROP TABLE IF EXISTS "SessionsBarbers";
DROP TABLE IF EXISTS "BarberShops" CASCADE;
DROP TABLE IF EXISTS "Chains";
DROP TABLE IF EXISTS "Barbers";

