name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.2
      id: go

    - name: Check out code into the Go module directory
      git uses: actions/checkout@v3

    - name: Test
      run: make test
